apiVersion: v1
kind: PersistentVolume
metadata:
  name: pysaprk-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/Users/rgupta98/shared"